[package]
name = "txs"
description = "a blockchain"
version = "0.7.0"
authors = ["Aaron Lebo <aaron.matthew.lebo@gmail.com>"]
license = "ISC"
repository = "https://github.com/aaron-lebo/txs"

[dependencies]
bincode = "0.9"
rocksdb = "0.8"
serde = "1.0"
serde_derive = "1.0"
sha2 = "0.7"
